apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: pmacdonald
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/pmacdonald-harbor-project/app@sha256:3b445c734d2a568157198e8763de10b1a9042f7690633c919347541267d0febb
        ports:
        - containerPort: 5000
