apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: pmacdonald
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/pmacdonald-harbor-project/db@sha256:204dd5eb1108e6f54a7819aae5588d855ba4fd08e35b55795012074728b9a70b
        ports:
        - containerPort: 5432
